# https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/customizing-dependabot-security-prs

version: 2
updates:

# add a new entry for the Python package manager
  - package-ecosystem: "pip"
    directory: "./app/py"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    assignees:
      - "andrew-scoppa"
    reviewers:
      - "Atmosera-adv-sec-prep/sec-man"
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    commit-message:
      # Prefix all commit messages with "Python: "
      prefix: "python"

# add a new entry for the JSON package manager
  - package-ecosystem: "npm"
    directory: "./app/js"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    assignees:
      - "andrew-scoppa"
    reviewers:
      - "andrew-scoppa"
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "npm"